// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBvGJ2vBkB_nqKaOEZsQ-aOjLl9eQBGQ9A',
    appId: '1:924845283434:web:1cb66f7c03971c84ac1213',
    messagingSenderId: '924845283434',
    projectId: 'podcastplayer-305a1',
    authDomain: 'podcastplayer-305a1.firebaseapp.com',
    storageBucket: 'podcastplayer-305a1.appspot.com',
    measurementId: 'G-6L253F5P7X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD_cyxLful-Lr6QKw-32vQcaD2VW7iA0Bc',
    appId: '1:924845283434:android:172bbce5c2a28a60ac1213',
    messagingSenderId: '924845283434',
    projectId: 'podcastplayer-305a1',
    storageBucket: 'podcastplayer-305a1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAdy7Z9349adJRB11m2n9Y3SkaBfkPtmAo',
    appId: '1:924845283434:ios:bd1fb321f43c8dfdac1213',
    messagingSenderId: '924845283434',
    projectId: 'podcastplayer-305a1',
    storageBucket: 'podcastplayer-305a1.appspot.com',
    iosBundleId: 'com.example.player',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAdy7Z9349adJRB11m2n9Y3SkaBfkPtmAo',
    appId: '1:924845283434:ios:bd1fb321f43c8dfdac1213',
    messagingSenderId: '924845283434',
    projectId: 'podcastplayer-305a1',
    storageBucket: 'podcastplayer-305a1.appspot.com',
    iosBundleId: 'com.example.player',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBvGJ2vBkB_nqKaOEZsQ-aOjLl9eQBGQ9A',
    appId: '1:924845283434:web:ace20c5f5a1a72f0ac1213',
    messagingSenderId: '924845283434',
    projectId: 'podcastplayer-305a1',
    authDomain: 'podcastplayer-305a1.firebaseapp.com',
    storageBucket: 'podcastplayer-305a1.appspot.com',
    measurementId: 'G-23ZB1PBG10',
  );
}
